server:
  port: 9004

spring:
  application:
    name: auth-service

eureka:
  instance:
    hostname: localhost

jwt:
  secret: PrasomKaewChanaKarn1009200012345678901009200012345678901
  expiration: 86400

